version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: pace_mobile
      MYSQL_USER: pace
      MYSQL_PASSWORD: pace
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  mysql-test:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: pace_mobile_test
      MYSQL_USER: pace
      MYSQL_PASSWORD: test
    ports:
      - 3307:3306

volumes:
  mysql: {}
