version: "3.3"
services:
  pace-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=pace_mobile
      - MYSQL_USER=pace
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - private
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  pace-mobile-backend:
    image: pace-mobile-backend
    depends_on:
      - pace-mysql
    networks:
      - public
      - private
    ports:
      - 3001:3001
    environment:
      - CONFIG_ENV=${CONFIG_ENV}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - ONESIGNAL_APIKEY=${ONESIGNAL_APIKEY}
      - ONESIGNAL_APPID=${ONESIGNAL_APPID}
    entrypoint: yarn run start
networks:
  public:
  private:
    internal: true
volumes:
  mysql: {}
